"""
Markdown Templates for Memory System.
Provides consistent formatting for daily logs, medical records, and other documents.
"""

from datetime import date, datetime
from typing import List, Dict, Any


def daily_log_template(
    date: date,
    diet: List[Dict[str, Any]],
    fitness: Dict[str, Any],
    conversations: List[Dict[str, Any]],
    summary: str = ""
) -> str:
    """
    Generate daily log markdown template.
    
    Args:
        date: Date of the log
        diet: List of meals/food entries
        fitness: Fitness data (steps, heart rate, activity)
        conversations: Key conversation points
        summary: Daily summary
        
    Returns:
        str: Formatted markdown content
    """
    md = f"""# Daily Log - {date.isoformat()}

## Summary
{summary if summary else "_No summary yet_"}

---

## 🍽️ Diet Log

"""
    
    if diet:
        for idx, meal in enumerate(diet, 1):
            meal_time = meal.get('time', 'N/A')
            meal_name = meal.get('name', 'Unknown')
            calories = meal.get('calories', 'N/A')
            gi_value = meal.get('gi_value', 'N/A')
            description = meal.get('description', '')
            
            md += f"""### Meal {idx} - {meal_time}
**Food**: {meal_name}  
**Calories**: {calories} kcal  
**GI Value**: {gi_value}  
**Description**: {description}  
**Analysis**: {meal.get('analysis', '_Pending analysis_')}

"""
    else:
        md += "_No meals recorded today_\n\n"
    
    md += """---

## 🏃 Fitness & Activity

"""
    
    if fitness:
        md += f"""**Steps**: {fitness.get('steps', 'N/A')}  
**Active Energy**: {fitness.get('active_energy', 'N/A')} kcal  
**Heart Rate**: {fitness.get('heart_rate', 'N/A')} bpm (avg)  
**Exercise Minutes**: {fitness.get('exercise_minutes', 'N/A')} min  

### Analysis
{fitness.get('analysis', '_Pending analysis_')}

"""
    else:
        md += "_No fitness data recorded today_\n\n"
    
    md += """---

## 💬 Key Conversations

"""
    
    if conversations:
        for conv in conversations:
            time = conv.get('time', 'N/A')
            topic = conv.get('topic', 'General')
            summary_text = conv.get('summary', '')
            
            md += f"""### {time} - {topic}
{summary_text}

"""
    else:
        md += "_No conversations recorded today_\n\n"
    
    md += """---

## 📊 Health Indicators
_This section will be auto-populated with health data trends_

---

*Generated by HealthGuard AI*
"""
    
    return md


def medical_record_template(
    record_id: str,
    analysis_date: datetime,
    extracted_data: Dict[str, Any],
    trends: List[Dict[str, Any]],
    recommendations: List[str]
) -> str:
    """
    Generate medical record analysis markdown template.
    
    Args:
        record_id: Unique identifier for the record
        analysis_date: When the analysis was performed
        extracted_data: Data extracted from the medical record
        trends: Trend analysis
        recommendations: Medical recommendations
        
    Returns:
        str: Formatted markdown content
    """
    md = f"""# Medical Record Analysis - {record_id}

**Analysis Date**: {analysis_date.isoformat()}  
**Record ID**: {record_id}

---

## 📋 Extracted Data

"""
    
    if extracted_data:
        for key, value in extracted_data.items():
            md += f"- **{key}**: {value}\n"
    else:
        md += "_No data extracted_\n"
    
    md += """
---

## 📈 Trends & Observations

"""
    
    if trends:
        for trend in trends:
            indicator = trend.get('indicator', 'Unknown')
            direction = trend.get('direction', 'stable')
            note = trend.get('note', '')
            
            direction_emoji = {
                'up': '📈',
                'down': '📉',
                'stable': '➡️'
            }.get(direction, '➡️')
            
            md += f"""### {direction_emoji} {indicator}
{note}

"""
    else:
        md += "_No trends identified_\n\n"
    
    md += """---

## 💡 Recommendations

"""
    
    if recommendations:
        for idx, rec in enumerate(recommendations, 1):
            md += f"{idx}. {rec}\n"
    else:
        md += "_No recommendations at this time_\n"
    
    md += """
---

## ⚠️ Important Notes
- This analysis is AI-generated and should not replace professional medical advice
- Please consult with your healthcare provider for interpretation and treatment decisions

---

*Generated by HealthGuard AI Medical Agent*
"""
    
    return md


def food_analysis_template(
    food_name: str,
    analysis_time: datetime,
    calories: float,
    gi_value: str,
    ir_assessment: str,
    recommendations: List[str]
) -> str:
    """
    Generate food analysis markdown snippet.
    
    Args:
        food_name: Name of the food
        analysis_time: When analysis was performed
        calories: Estimated calories
        gi_value: Glycemic Index value/category
        ir_assessment: Assessment for insulin resistance
        recommendations: Dietary recommendations
        
    Returns:
        str: Formatted markdown snippet
    """
    md = f"""#### 🍽️ {food_name}
**Time**: {analysis_time.strftime('%H:%M:%S')}  
**Calories**: ~{calories} kcal  
**GI Value**: {gi_value}  

**IR Assessment**: {ir_assessment}

**Recommendations**:
"""
    
    for rec in recommendations:
        md += f"- {rec}\n"
    
    return md


def fitness_analysis_template(
    analysis_date: date,
    steps: int,
    active_energy: float,
    exercise_minutes: int,
    heart_rate_avg: Optional[float],
    assessment: str
) -> str:
    """
    Generate fitness analysis markdown snippet.
    
    Args:
        analysis_date: Date of analysis
        steps: Step count
        active_energy: Active energy burned (kcal)
        exercise_minutes: Exercise duration (minutes)
        heart_rate_avg: Average heart rate
        assessment: Overall assessment
        
    Returns:
        str: Formatted markdown snippet
    """
    from typing import Optional
    
    md = f"""#### 🏃 Activity Summary - {analysis_date.isoformat()}

**Metrics**:
- Steps: {steps:,}
- Active Energy: {active_energy} kcal
- Exercise: {exercise_minutes} minutes
"""
    
    if heart_rate_avg:
        md += f"- Avg Heart Rate: {heart_rate_avg:.0f} bpm\n"
    
    md += f"""
**Assessment**: {assessment}
"""
    
    return md
